# Generated by Django 2.2.1 on 2019-05-16 13:28

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0006_auto_20190516_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=django_fsm.FSMField(default='order_placed', max_length=50),
        ),
    ]
