# Generated by Django 2.2.1 on 2019-05-17 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0007_order_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
    ]
