# Generated by Django 2.1.7 on 2019-03-08 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0007_order_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
    ]
