# Generated by Django 2.1.7 on 2019-03-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0011_order_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='SpgatewaySlug',
            field=models.SlugField(max_length=20, null=True, unique=True),
        ),
    ]
